import React from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
	faCheckSquare,
	faCoffee,
	faBed,
} from "@fortawesome/fontawesome-free-solid";
import { Container, Row, Col } from "react-bootstrap";
import Button from "react-bootstrap/Button";
import "bootstrap/dist/css/bootstrap.min.css";
import Jumbotron from "react-bootstrap/Jumbotron";
import "../stylesheets/homepage.component.css";
import axios from "axios";

class Homepage extends React.Component {
	handleClick(event) {
		axios.get("http://0.0.0.0:5000/available").then((response) => {
			console.log(response.data);
		});
	}

	render() {
		return (
			<div>
				<Jumbotron className="jumbo-style">
					<br />
					<br />
					<Container fluid="md">
						<Row>
							<Col>
								<FontAwesomeIcon
									icon={faBed}
									size="3x"
									onClick={this.handleClick}
									id="1"
								/>
							</Col>
							<Col>
								<FontAwesomeIcon
									icon={faBed}
									size="3x"
									onClick={this.handleClick}
									id="2"
								/>
							</Col>
							<Col>
								<FontAwesomeIcon
									icon={faBed}
									size="3x"
									onClick={this.handleClick}
									id="3"
								/>
							</Col>
							<Col>
								<FontAwesomeIcon
									icon={faBed}
									size="3x"
									onClick={this.handleClick}
									id="4"
								/>
							</Col>
							<Col>
								<FontAwesomeIcon
									icon={faBed}
									size="3x"
									onClick={this.handleClick}
									id="5"
								/>
							</Col>
							<Col>
								<FontAwesomeIcon
									icon={faBed}
									size="3x"
									onClick={this.handleClick}
									id="6"
								/>
							</Col>
						</Row>
						<Row>
							<Col>
								<FontAwesomeIcon
									icon={faBed}
									size="3x"
									onClick={this.handleClick}
									id="7"
								/>
							</Col>
							<Col>
								<FontAwesomeIcon
									icon={faBed}
									size="3x"
									onClick={this.handleClick}
									id="8"
								/>
							</Col>
							<Col>
								<FontAwesomeIcon
									icon={faBed}
									size="3x"
									onClick={this.handleClick}
									id="9"
								/>
							</Col>
							<Col>
								<FontAwesomeIcon
									icon={faBed}
									size="3x"
									onClick={this.handleClick}
									id="10"
								/>
							</Col>
							<Col>
								<FontAwesomeIcon
									icon={faBed}
									size="3x"
									onClick={this.handleClick}
									id="11"
								/>
							</Col>
							<Col>
								<FontAwesomeIcon
									icon={faBed}
									size="3x"
									onClick={this.handleClick}
									id="12"
								/>
							</Col>
						</Row>
						<Row>
							<Col>
								<FontAwesomeIcon
									icon={faBed}
									size="3x"
									onClick={this.handleClick}
									id="13"
								/>
							</Col>
							<Col>
								<FontAwesomeIcon
									icon={faBed}
									size="3x"
									onClick={this.handleClick}
									id="14"
								/>
							</Col>
							<Col>
								<FontAwesomeIcon
									icon={faBed}
									size="3x"
									onClick={this.handleClick}
									id="15"
								/>
							</Col>
							<Col>
								<FontAwesomeIcon
									icon={faBed}
									size="3x"
									onClick={this.handleClick}
									id="16"
								/>
							</Col>
							<Col>
								<FontAwesomeIcon
									icon={faBed}
									size="3x"
									onClick={this.handleClick}
									id="17"
								/>
							</Col>
							<Col>
								<FontAwesomeIcon
									icon={faBed}
									size="3x"
									onClick={this.handleClick}
									id="18"
								/>
							</Col>
						</Row>
						<Row>
							<Col>
								<FontAwesomeIcon
									icon={faBed}
									size="3x"
									onClick={this.handleClick}
									id="19"
								/>
							</Col>
							<Col>
								<FontAwesomeIcon
									icon={faBed}
									size="3x"
									onClick={this.handleClick}
									id="20"
								/>
							</Col>
							<Col>
								<FontAwesomeIcon
									icon={faBed}
									size="3x"
									onClick={this.handleClick}
									id="21"
								/>
							</Col>
							<Col>
								<FontAwesomeIcon
									icon={faBed}
									size="3x"
									onClick={this.handleClick}
									id="22"
								/>
							</Col>
							<Col>
								<FontAwesomeIcon
									icon={faBed}
									size="3x"
									onClick={this.handleClick}
									id="23"
								/>
							</Col>
							<Col>
								<FontAwesomeIcon
									icon={faBed}
									size="3x"
									onClick={this.handleClick}
									id="24"
								/>
							</Col>
						</Row>
						<Row>
							<Col>
								<FontAwesomeIcon
									icon={faBed}
									size="3x"
									onClick={this.handleClick}
									id="25"
								/>
							</Col>
							<Col>
								<FontAwesomeIcon
									icon={faBed}
									size="3x"
									onClick={this.handleClick}
									id="26"
								/>
							</Col>
							<Col>
								<FontAwesomeIcon
									icon={faBed}
									size="3x"
									onClick={this.handleClick}
									id="27"
								/>
							</Col>
							<Col>
								<FontAwesomeIcon
									icon={faBed}
									size="3x"
									onClick={this.handleClick}
									id="28"
								/>
							</Col>
							<Col>
								<FontAwesomeIcon
									icon={faBed}
									size="3x"
									onClick={this.handleClick}
									id="29"
								/>
							</Col>
							<Col>
								<FontAwesomeIcon
									icon={faBed}
									size="3x"
									onClick={this.handleClick}
									id="30"
								/>
							</Col>
						</Row>
						<Row>
							<Col>
								<FontAwesomeIcon
									icon={faBed}
									size="3x"
									onClick={this.handleClick}
									id="31"
								/>
							</Col>
							<Col>
								<FontAwesomeIcon
									icon={faBed}
									size="3x"
									onClick={this.handleClick}
									id="32"
								/>
							</Col>
							<Col>
								<FontAwesomeIcon
									icon={faBed}
									size="3x"
									onClick={this.handleClick}
									id="33"
								/>
							</Col>
							<Col>
								<FontAwesomeIcon
									icon={faBed}
									size="3x"
									onClick={this.handleClick}
									id="34"
								/>
							</Col>
							<Col>
								<FontAwesomeIcon
									icon={faBed}
									size="3x"
									onClick={this.handleClick}
									id="35"
								/>
							</Col>
							<Col>
								<FontAwesomeIcon
									icon={faBed}
									size="3x"
									onClick={this.handleClick}
									id="36"
								/>
							</Col>
						</Row>
						<br />

						<Button> Book</Button>
					</Container>
				</Jumbotron>
			</div>
		);
	}
}

export default Homepage;
